"""adding tables

Revision ID: 4de5ca64093a
Revises: 
Create Date: 2026-04-06 18:36:58.479523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de5ca64093a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_table('manual_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('price_listed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('brand_model_idx', 'manual_lookups', ['brand', 'model'], unique=False)
    op.create_index(op.f('ix_manual_lookups_brand'), 'manual_lookups', ['brand'], unique=False)
    op.create_index(op.f('ix_manual_lookups_mode'), 'manual_lookups', ['mode'], unique=False)
    op.create_index(op.f('ix_manual_lookups_model'), 'manual_lookups', ['model'], unique=False)
    op.create_index(op.f('ix_manual_lookups_user_id'), 'manual_lookups', ['user_id'], unique=False)
    op.create_index(op.f('ix_manual_lookups_vin'), 'manual_lookups', ['vin'], unique=False)
    op.create_table('parsed_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_data', sa.String(), nullable=False),
    sa.Column('vin', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('transmission', sa.String(), nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('price_listed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('brand_model_idx', 'parsed_lookups', ['brand', 'model'], unique=False)
    op.create_index(op.f('ix_parsed_lookups_brand'), 'parsed_lookups', ['brand'], unique=False)
    op.create_index(op.f('ix_parsed_lookups_model'), 'parsed_lookups', ['model'], unique=False)
    op.create_index(op.f('ix_parsed_lookups_user_id'), 'parsed_lookups', ['user_id'], unique=False)
    op.create_index(op.f('ix_parsed_lookups_vin'), 'parsed_lookups', ['vin'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('last_price', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_index('users_urls', 'watchlist', ['user_id', 'url'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('price_diff', sa.Integer(), nullable=False),
    sa.Column('price_diff_percents', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('noticed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_watchlist_id'), 'price_alerts', ['watchlist_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_lookup_id', sa.Integer(), nullable=True),
    sa.Column('parsed_lookup_id', sa.Integer(), nullable=True),
    sa.Column('predicted_price', sa.Integer(), nullable=False),
    sa.Column('price_deviation_percent', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['manual_lookup_id'], ['manual_lookups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parsed_lookup_id'], ['parsed_lookups.id'], onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_verdict'), 'verdicts', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_verdict'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_price_alerts_watchlist_id'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index('users_urls', table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_parsed_lookups_vin'), table_name='parsed_lookups')
    op.drop_index(op.f('ix_parsed_lookups_user_id'), table_name='parsed_lookups')
    op.drop_index(op.f('ix_parsed_lookups_model'), table_name='parsed_lookups')
    op.drop_index(op.f('ix_parsed_lookups_brand'), table_name='parsed_lookups')
    op.drop_index('brand_model_idx', table_name='parsed_lookups')
    op.drop_table('parsed_lookups')
    op.drop_index(op.f('ix_manual_lookups_vin'), table_name='manual_lookups')
    op.drop_index(op.f('ix_manual_lookups_user_id'), table_name='manual_lookups')
    op.drop_index(op.f('ix_manual_lookups_model'), table_name='manual_lookups')
    op.drop_index(op.f('ix_manual_lookups_mode'), table_name='manual_lookups')
    op.drop_index(op.f('ix_manual_lookups_brand'), table_name='manual_lookups')
    op.drop_index('brand_model_idx', table_name='manual_lookups')
    op.drop_table('manual_lookups')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
