"""tables correcting

Revision ID: 7829b149f288
Revises: 62eb009a0483
Create Date: 2026-04-07 08:43:55.474097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7829b149f288'
down_revision: Union[str, Sequence[str], None] = '62eb009a0483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_lookups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_manual_lookups_vin'), table_name='manual_lookups')
    op.drop_column('manual_lookups', 'vin')
    op.add_column('parsed_lookups', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_parsed_lookups_vin'), table_name='parsed_lookups')
    op.drop_column('parsed_lookups', 'vin')
    op.add_column('verdicts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('watchlist', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('watchlist', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('watchlist', 'deleted_at')
    op.drop_column('verdicts', 'deleted_at')
    op.add_column('parsed_lookups', sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_parsed_lookups_vin'), 'parsed_lookups', ['vin'], unique=False)
    op.drop_column('parsed_lookups', 'deleted_at')
    op.add_column('manual_lookups', sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_manual_lookups_vin'), 'manual_lookups', ['vin'], unique=False)
    op.drop_column('manual_lookups', 'deleted_at')
    # ### end Alembic commands ###
